site_name: Максим Толстых
site_description: В поиске данных, инсайтов, мониторинге и анализе актуальных навыков.
site_author: Максим Толстых aka DocItSage
site_url: https://docitsage.github.io/

theme:
  name: material
  language: ru
  features:
    - navigation.tabs
    - navigation.top
    - content.tooltips
    - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/lightbulb
        name: Переключить на тёмную тему
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/lightbulb-outline
        name: Переключить на светлую тему

nav:
  - Главная: index.md
  - Проекты:
      - ЧГ: подарочные карты
  - Артефакты:
    - R&D: ms-vacancy/docs/rnd.md
    - C4: howto.md
    - WBS: wbs.md
    - JSON: json.md

plugins:
  - search
  - plantuml:
      puml_url: "http://www.plantuml.com/plantuml/"
  - social:
      cards_layout_options:
        background_color: "#1962ff"

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/docitsage
    - icon: fontawesome/brands/telegram
      link: https://t.me/DocItSage

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - abbr