name: CI/CD for MkDocs 
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        #with:
        #  submodules: recursive
        #  token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Test SSH connection
        run: ssh -T git@github.com
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: Clone VacancyDataMiner repository
        run: |
          mkdir -p docs/ms-vacancy
          git clone git@github.com:DocItSage/VacancyDataMiner.git docs/ms-vacancy
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: ~/.cache 
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material 
      - run: mkdocs gh-deploy --force
      - name: Debug information
        run: |
          echo "Checking directory structure..."
          ls -la
          echo "Checking SSH config..."
          cat ~/.ssh/config || true
          echo "Checking SSH keys..."
          ls -la ~/.ssh || true
          echo "Testing SSH connection..."
          ssh -T git@github.com